---
# tasks file for load_balance
- name: Download and install haproxy
  package: name=haproxy state=present

- name: Configure the haproxy cnf file with hosts
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: 0644
    validate: haproxy -f %s -c -q
  notify: restart haproxy

- name: Start the haproxy service
  systemd: name=haproxy state=started enabled=yes
